### ISSUE TITLE
Bug when reloading data

### ISSUE THREAD

**Issue by alexandre-g** [XuYanci/GLViewPagerViewController-Swift#1]
Hi there, thanks for the great library! Well built.

I have encountered a bug when reloading data that others may face, so just wanted to share the solution.

If you are showing some pages and then change the dataset and call`reloadData()`, you can have some issues with caching. I've tried looking and it seems like `pageViewController` preloads the next page and stores it in `.childViewControllers` array. So after the reload, it would try load the cached version when changing to next page and crash for me.
There is a known "fix" for this and that is to either use `setViewControllers` with animated flag as false, or to redispatch the statement on the main thread again:
```
onMain() { [weak self] in
            self?.pageViewController.setViewControllers([self!.contentViewControllers[pageIndex]], direction: direction, animated: true, completion: nil)
}
```

**Comment by XuYanci** [comment]
thank u , i will resole this issue later
